version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - echo ap-southeast-1
      - aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 928920371678.dkr.ecr.ap-southeast-1.amazonaws.com
  build:
    commands:          
      - docker build -t bharath:latest .
      - docker tag bharath:latest 928920371678.dkr.ecr.ap-southeast-1.amazonaws.com/bharath:latest      
  post_build:
    commands:
      - docker push 928920371678.dkr.ecr.ap-southeast-1.amazonaws.com/bharath:latest
      - printf '[{"name":"bharath","imageUri":"928920371678.dkr.ecr.ap-southeast-1.amazonaws.com/bharath:latest"}]' $REPOSITORY_URI:928920371678.dkr.ecr.ap-southeast-1.amazonaws.com/bharath > imagedefinitions.json
artifacts:
  files:
    - '**/*'      
      